# Generated by Django 4.2.7 on 2025-08-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlanalytics',
            name='city',
        ),
        migrations.RemoveField(
            model_name='urlanalytics',
            name='country',
        ),
        migrations.RemoveField(
            model_name='urlanalytics',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='urlanalytics',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='urlanalytics',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='urlanalytics',
            name='region',
        ),
    ]
